/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvatarMenu: typeof import('./src/components/Avatar/AvatarMenu.vue')['default']
    DarkModeToggle: typeof import('./src/components/Themes/DarkModeToggle.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FullScreen: typeof import('./src/components/Themes/FullScreen.vue')['default']
    Header1: typeof import('./src/components/layouts/Header1.vue')['default']
    IconFontIcon: typeof import('./src/components/Icon/IconFontIcon.vue')['default']
    Iconify: typeof import('./src/components/Icon/Iconify.vue')['default']
    IconList: typeof import('./src/components/Icon/IconList.vue')['default']
    IconPicker: typeof import('./src/components/Icon/IconPicker.vue')['default']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    MenuItem: typeof import('./src/components/Menu/MenuItem.vue')['default']
    NetIcon: typeof import('./src/components/Icon/NetIcon.vue')['default']
    Notice: typeof import('./src/components/Notice/Notice.vue')['default']
    NoticeMessageList: typeof import('./src/components/Notice/NoticeMessageList.vue')['default']
    Notification: typeof import('./src/components/Notice/Notification.vue')['default']
    ReloadPrompt: typeof import('./src/components/other/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./src/components/Menu/SubMenu.vue')['default']
    SvgIcon: typeof import('./src/components/Icon/SvgIcon.vue')['default']
    ThemeSetting: typeof import('./src/components/Themes/ThemeSetting.vue')['default']
  }
}
