/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aa: typeof import('./src/components/IconFontIcon.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    IconFontIcon: typeof import('./src/components/IconFontIcon.vue')['default']
    IconList: typeof import('./src/components/IconList.vue')['default']
    NetIcon: typeof import('./src/components/NetIcon.vue')['default']
    NoticeNotification: typeof import('./src/components/notice/Notification.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    ThemesDarkModeToggle: typeof import('./src/components/Themes/DarkModeToggle.vue')['default']
    ThemesFullScreen: typeof import('./src/components/Themes/FullScreen.vue')['default']
    ThemesTest: typeof import('./src/components/Themes/Test.vue')['default']
  }
}
