/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Header: typeof import('./src/components/Layouts/Header.vue')['default']
    HeaderTabs: typeof import('./src/components/Layouts/HeaderTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VpAudioPlayer: typeof import('el-admin-components')['VpAudioPlayer']
    VpAvatarMenu: typeof import('el-admin-components')['VpAvatarMenu']
    VpBreadcrumb: typeof import('el-admin-components')['VpBreadcrumb']
    VpCharts: typeof import('el-admin-components')['VpCharts']
    VpDarkModeToggle: typeof import('el-admin-components')['VpDarkModeToggle']
    VpEditor: typeof import('el-admin-components')['VpEditor']
    VpForm: typeof import('el-admin-components')['VpForm']
    VpFullScreen: typeof import('el-admin-components')['VpFullScreen']
    VpHeader: typeof import('el-admin-components')['VpHeader']
    VpHeaderTabs: typeof import('el-admin-components')['VpHeaderTabs']
    VpIconify: typeof import('el-admin-components')['VpIconify']
    VpIconList: typeof import('el-admin-components')['VpIconList']
    VpIconPicker: typeof import('el-admin-components')['VpIconPicker']
    VpMenu: typeof import('el-admin-components')['VpMenu']
    VpNotice: typeof import('el-admin-components')['VpNotice']
    VpTable: typeof import('el-admin-components')['VpTable']
    VpThemeSettings: typeof import('el-admin-components')['VpThemeSettings']
    VpVideoPlayer: typeof import('el-admin-components')['VpVideoPlayer']
    VpVueEcharts: typeof import('el-admin-components')['VpVueEcharts']
  }
}
